spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/testdb
        username: root
        password: sql1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect