spring:
    datasource:
        url: jdbc:postgresql://localhost/postgres
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: sql1234
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show-sql: true
                format: true
        hibernate:
            ddl-auto: create-drop