spring:
    datasource:
        url: jdbc:mariadb://127.0.0.1:3307/testdb
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 
    jpa:
        database-platform: org.hibernate.dialect.MariaDB106Dialect
        properties:
            hibernate:
                show-sql: true
                format: true 
        hibernate:
            ddl-auto: create-drop
